

const Booking = () => {
    return (
        <div >
           <div className="text-center my-10 space-y-5 font-bold">
           <h1 className="">Why Booking with us</h1>
            <h2 className="md:text-4xl md:mx-96">
                Convenient and Easy Tour
                Booking Process
            </h2>
           </div>
           <div className="flex gap-4">
            <div className="border-r border-dashed text-center">
               <div>
               <img  className="mx-auto" src="https://i.ibb.co/B2jgYtC/icons8-tour-80.png" alt="" />
               </div>
               <div className="mt-3 space-y-3">
               <h1 className="text-xl font-bold">Reliable Tours</h1>
                <p className="text-gray-500">We insist on a very high tour quality and therefore only work with qualified and professional tour companies.</p>
               </div>
            </div>
            <div className="border-r border-dashed   text-center">
               <div>
               <img className="mx-auto" src="https://i.ibb.co/2dcXcLw/icons8-booking-80.png" alt="" />
               </div>
              <div className="mt-3 space-y-3">
              <h1 className="text-xl font-bold">Fast Booking</h1>
                <p className="text-gray-500">Journey is automatically offsetting the carbon footprint generated by all tour bookings, for online package tour booking platforms.</p>
              </div>
            </div>
            <div className="text-center"> 
                <div>
                <img className="mx-auto" src="https://i.ibb.co/3yQTnVB/icons8-trips-100.png" alt="" />
                </div>
                <div className=" space-y-3">
                <h1 className="text-xl font-bold">Pesonalized Trips</h1>
                <p className="text-gray-500">Our local travel experts will design a trip that matches your unique interests and special requirements, booking everything</p>
                </div>
            </div>
           </div>
        </div>
    );
};

export default Booking;